name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Create gradle cache directory
        run: mkdir -p ~/.gradle/wrapper
        
      - name: Build Debug APK
        run: |
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace --info
        
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: tiger-study-plan-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          
      - name: Build Release APK
        run: |
          ./gradlew assembleRelease --stacktrace --info
        
      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: tiger-study-plan-release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk