name: Build Android APK

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Accept Android SDK licenses
      run: |
        echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses || true
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build APK
      run: |
        ./gradlew --version
        ./gradlew tasks
        ./gradlew :app:assembleDebug --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: tiger-study-plan-apk
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 30